### ISSUE TITLE
README Issue when installing in windows

### ISSUE THREAD

**Issue by IlayMalinyak** [lgbouma/gyro-interp#3]
Hi when using 'pip install gyrointerp' on windows machine i get the following output:
`(kepler2) PS C:\Users\Ilay\projects\kepler\data> pip install gyrointerp                          
Collecting gyrointerp
  Using cached gyrointerp-0.5.tar.gz (13.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Ilay\AppData\Local\Temp\pip-install-uwblpyfz\gyrointerp_652edb1429a94ee19ffea760265cd814\setup.py", line 58, in <module>
          long_description=readme(),
        File "C:\Users\Ilay\AppData\Local\Temp\pip-install-uwblpyfz\gyrointerp_652edb1429a94ee19ffea760265cd814\setup.py", line 30, in readme
          return f.read()
        File "C:\Users\Ilay\anaconda3\envs\kepler2\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2527: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`
followed by [this](https://github.com/abhishekkrthakur/diffuzers/issues/23) issue i cloned the repo and deleted the alarm imoji and it seems to work. 
you might want to edit the README so it wouldn't happen with pip install

thanks

Ilay

**Comment by lgbouma** [comment]
Hi Ilay,

Thank you for raising this issue!

This is indeed because windows and mac/linux have different default file encodings.  Windows sometimes defaults to `cp1252`; emoji requires `utf-8`.  I'd like to keep the emojis :-)

The edit at https://github.com/lgbouma/gyro-interp/commit/b80c5a368d53fa4cc7f90d41c22b87f8eabafca5 should fix this behavior on windows, and I've committed it to the `dev` branch.  It'll be incorporated into a future version release in the next few months.  For the time being, this seems minor enough (and since you were able to fix it!) to not yet warrant a dedicated release bump.

Thank you again!
Luke
